FROM oven/bun:1

WORKDIR /app

COPY frontend/package.json frontend/bun.lock ./

RUN bun install --frozen-lockfile

COPY frontend/ .

EXPOSE 8000

CMD ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "8000"]